"""Rosa's Pizza: starter code for O712 Assignment 1.

Do not edit this file.

Time blocks
    Lunch          11am-2pm, every day
    Weekday eve    5-8pm, Monday-Thursday
    Fri/Sat eve    6-9pm, Friday and Saturday
    Other          everything else

All figures cover four weeks of operation.
"""
import numpy as np

ZONES = ["Central", "North", "Far West"]
TIME_BLOCKS = ["Lunch", "Weekday eve", "Fri/Sat eve", "Other"]

COSTS = {
    "refund": 10.0,       # $ credit given on each late order
    "churn_orders": 1.8,  # future orders lost after one late delivery
    "margin": 9.0,        # $ profit on one order
}

PROMISE = 45  # minutes: today's promised delivery time, every zone


def delivery_times(zone, time_block, promise=PROMISE, seed=None):
    """Simulate four weeks of orders in one zone and time block.

    Returns a NumPy array with one delivery time (minutes) per order.
    len() of the array is the number of orders Rosa receives.

    - A longer promise attracts fewer orders.
    - More orders make every delivery slower.

    This is a simulator: each call gives different results. Pass a
    number as `seed` (e.g. seed=1) to get the same results every time.
    """
    if zone not in ZONES:
        raise ValueError(f"zone must be one of {ZONES}, got {zone!r}")
    if time_block not in TIME_BLOCKS:
        raise ValueError(f"time_block must be one of {TIME_BLOCKS}, got {time_block!r}")
    if promise <= 0:
        raise ValueError(f"promise must be a positive number of minutes, got {promise!r}")
    rng = np.random.default_rng(seed)
    n_orders = int(round(_expected_orders(zone, time_block, promise)))
    if n_orders == 0:
        return np.array([])  # promise so long that nobody orders
    load = n_orders / _BASE_ORDERS[(zone, time_block)]
    # Busier -> slower. Even with no other orders, cooking and driving take
    # time, so the median never drops below 60% of today's median.
    median = _BASE_MEDIAN[(zone, time_block)] * (0.6 + 0.4 * load)
    times = rng.lognormal(np.log(median), 0.3, n_orders)
    return np.round(times, 1)


# ---------------------------------------------------------------------------
# Internal settings. You do not need to read or use anything below this line.
# ---------------------------------------------------------------------------
_BASE_ORDERS = {  # orders at the 45-minute promise
    ("Central", "Lunch"): 260, ("Central", "Weekday eve"): 330,
    ("Central", "Fri/Sat eve"): 190, ("Central", "Other"): 190,
    ("North", "Lunch"): 190, ("North", "Weekday eve"): 250,
    ("North", "Fri/Sat eve"): 150, ("North", "Other"): 160,
    ("Far West", "Lunch"): 120, ("Far West", "Weekday eve"): 170,
    ("Far West", "Fri/Sat eve"): 210, ("Far West", "Other"): 192,
}
_BASE_MEDIAN = {  # median delivery minutes at the 45-minute promise
    ("Central", "Lunch"): 26.6, ("Central", "Weekday eve"): 28.9,
    ("Central", "Fri/Sat eve"): 31.6, ("Central", "Other"): 25.6,
    ("North", "Lunch"): 28.2, ("North", "Weekday eve"): 31.1,
    ("North", "Fri/Sat eve"): 36.4, ("North", "Other"): 27.5,
    ("Far West", "Lunch"): 30.1, ("Far West", "Weekday eve"): 34.6,
    ("Far West", "Fri/Sat eve"): 42.0, ("Far West", "Other"): 29.5,
}


def _share(promise):
    return 1 / (1 + np.exp((promise - 60) / 8))


def _expected_orders(zone, time_block, promise):
    return _BASE_ORDERS[(zone, time_block)] * _share(promise) / _share(PROMISE)
